Repository twenty-three-23/peech, pull requests merged in 2024-07, with the labels that each got.

#126 TT-169 controller 계층 구조 변경
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
  src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java
  src/main/java/com/twentythree/peech/script/controller/ThemeController.java
  src/main/java/com/twentythree/peech/script/dto/request/ParagraphsRequestDTO.java
  src/main/java/com/twentythree/peech/script/dto/response/SaveScriptAndSentenceResponseDTO.java
  src/main/java/com/twentythree/peech/script/dto/response/SaveScriptAndSentencesResponseDTO.java
  src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
Labels: 수정

#121 TT-161 userId를 토큰에 담아 응답
  build.gradle
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
  src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/dto/response/CreateUserResponseDTO.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: 기능구현

#132 ! TT-173 cicd jwt env
  .github/workflows/cicd_dev.yml
Labels: 환경설정

#131 TT-171 re issuance user token
  src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/dto/response/UserIdTokenResponseDTO.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
Labels: 기능구현, 수정

#133 !TT-206 토큰 재발급 end point 추가
  src/main/java/com/twentythree/peech/user/controller/UserController.java
Labels: 버그

#134 TT-207 이미 가입된 유저 예외처리 [0.5/0.5]
  src/main/java/com/twentythree/peech/common/dto/UserAlreadyExistErrorVO.java
  src/main/java/com/twentythree/peech/common/exception/BaseException.java
  src/main/java/com/twentythree/peech/common/exception/UserAlreadyExistException.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
Labels: 기능구현

#147 TT-210 token을 header의 Authorization에서 조회
  src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
Labels: 수정

#150 TT-208 cicd update
  .github/workflows/cicd_dev.yml
Labels: 수정

#151 TT-208 actions/checkout
  .github/workflows/cicd_dev.yml
Labels: 버그

#155 fix: cicd
  .github/workflows/cicd_dev.yml
Labels: 수정

#156 fix: ci cd
  .github/workflows/cicd_dev.yml
Labels: 수정

#154 !TT-216 themes 조회시 theme이 하나만 조회됨
  src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java
  src/main/java/com/twentythree/peech/script/service/ThemeService.java
  src/main/resources/data.sql
Labels: 버그

#143 TT-205 modify script [2/8]
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
  src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/dto/ModifiedParagraphDTO.java
  src/main/java/com/twentythree/peech/script/dto/ParagraphAndExpectedTimeDTO.java
  src/main/java/com/twentythree/peech/script/dto/ParagraphDTO.java
  src/main/java/com/twentythree/peech/script/dto/ParagraphId.java
  src/main/java/com/twentythree/peech/script/dto/RedisSentenceDTO.java
  src/main/java/com/twentythree/peech/script/dto/RedisSentencesPerParagraphId.java
  src/main/java/com/twentythree/peech/script/dto/SentenceDTO.java
  src/main/java/com/twentythree/peech/script/dto/SentenceId.java
  src/main/java/com/twentythree/peech/script/dto/request/ModifiedScriptRequestDTO.java
  src/main/java/com/twentythree/peech/script/dto/response/ModifiedScriptResponseDTO.java
  src/main/java/com/twentythree/peech/script/dto/response/ModifyScriptResponseDTO.java
  src/main/java/com/twentythree/peech/script/repository/ScriptInMemoryRepository.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 기능구현

#182 TT-118 redis setting
  src/main/java/com/twentythree/peech/script/cache/CacheService.java
  src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
  src/test/java/com/twentythree/peech/script/service/ScriptRedisTemplateImplTest.java
Labels: 버그, 수정

#177 TT-215 credential이 null일 때 처리
  src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
Labels: 수정

#187 TT-228 data.sql 실행을 환경변수화
  .github/workflows/cicd_dev.yml
  src/main/resources/application.yml
Labels: 수정

#188 TT-215 token이 없으면 401에러
  src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
Labels: 수정

#185 TT-223 log 수집 [4/6]
  .gitignore
  src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java
  src/main/java/com/twentythree/peech/common/interceptor/RequestLogInterceptor.java
  src/main/java/com/twentythree/peech/config/interceptor/AuthInterceptorConfig.java
  src/main/java/com/twentythree/peech/config/interceptor/LogInterceptorConfig.java
  src/main/resources/application.yml
  src/main/resources/spring-logback.xml
Labels: 기능구현

#190 !TT-232 VersionEntity 복합키 설정
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionPk.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 버그

#192 !TT-233 log 출력을 위한 id 추출 interceptor에서 토큰이 x로 올때 값 처리
  src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java
Labels: 버그

#193 bug: TT-233
  src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java
Labels: 버그

#194 !TT-233 logging을 위해 userId를 가져올 때 에러 발생시 return true
  src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java
  src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
Labels: 버그

#196 TT-234 ThemeEntity DB 반영 값 변경 및 ScriptEntity fk 설정
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionEntity.java
Labels: 버그, 수정

#197 !TT-236 문장 생성이 안되는 버그
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/service/SentenceService.java
Labels: 버그

#199 !TT-237 메이저 스크립트 조회 불가
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
Labels: 버그

#200 !TT-237 테마 아래에 모든 메이저 버전이 생성됨
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
Labels: 버그

#201 !TT-237 소문자 이슈
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
Labels: 버그

#152 TT-174 메이저 버전들을 조회할 때 minor script의 개수를 포함한다 [1/1]
  src/main/java/com/twentythree/peech/script/dto/MajorScriptDTO.java
  src/main/java/com/twentythree/peech/script/dto/response/ThemesResponseDTO.java
  src/main/java/com/twentythree/peech/script/repository/VersionRepository.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 기능구현

#203 TT-241 대본Id를 통한 문단 조회
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
  src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java
  src/main/java/com/twentythree/peech/script/dto/ParagraphContent.java
  src/main/java/com/twentythree/peech/script/dto/response/ParagraphsResponseDTO.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 기능구현

#213 TT-245 사용 시간 기초로직 구현
  src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java
  src/main/java/com/twentythree/peech/usagetime/dto/AudioFileRequestDTO.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/CheckRemainingTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/RemainingTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/repository/UsageTimeRepository.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
Labels: 기능구현

#215 TT-266 themeId에 관계 없이 마이너 대본 전체 조회 버그
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
Labels: 버그

#216 TT-271 남은 시간 조회 응답 스펙변경 및 최대 음성 녹음 가능 시간 조회
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
  src/main/java/com/twentythree/peech/usagetime/constant/ConstantValue.java
  src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/dto/RemainingTimeDTO.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/TextAndSecondTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/repository/UsageTimeRepository.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
Labels: 기능구현, 수정

#218 TT-271 남은 시간, 최대 음성 녹음 시간 json 구조 변경
  src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/MaxAudioTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/TextAndSecondResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/TextAndSecondTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
Labels: 수정

#221 TT-273 테스트 데이터 추가
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java
  src/main/resources/data.sql
Labels: 수정

#227 TT-282 SentenceEntity Id를 uuid로 변경
  src/main/java/com/twentythree/peech/script/cache/CacheService.java
  src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/dto/SentenceDTO.java
  src/main/java/com/twentythree/peech/script/dto/SentenceId.java
  src/main/java/com/twentythree/peech/script/repository/SentenceRepository.java
  src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
  src/main/java/com/twentythree/peech/script/service/SentenceService.java
  src/main/java/com/twentythree/peech/script/stt/dto/response/SentenceDTO.java
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
  src/main/resources/data.sql
  src/test/java/com/twentythree/peech/script/service/ScriptRedisTemplateImplTest.java
Labels: 수정

#228 TT-273 대본 수정 기능 오류 해결
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 수정

#231 TT-286 대본 수정 응답 구성 변경
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
  src/main/java/com/twentythree/peech/script/dto/response/ModifyScriptResponseDTO.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 수정

#236 TT-292 문장 수장 코드 주석 추가
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 리팩토링

#238 TT-186 prod ci cd
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
Labels: 기능구현

#237 TT-291 대본 수정시 redis에 유저의 문장id정보가 마지막 하나만 저장되는 버그
  src/main/java/com/twentythree/peech/script/cache/CacheService.java
  src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 버그

#239 TT-252 docker volume
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
  .github/workflows/cicd_dev.yml
  Dockerfile
  src/main/resources/application.yml
  src/main/resources/spring-logback.xml
Labels: 기능구현, 수정

#243 TT-272 엔티티 양방향 참조 삭제
  src/main/java/com/twentythree/peech/common/exception/BaseException.java
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/ThemeEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionEntity.java
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
  src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
  src/main/java/com/twentythree/peech/script/service/ThemeService.java
  src/main/java/com/twentythree/peech/user/domain/UserEntity.java
Labels: 수정

#246 TT-272 theme id 가 2개 들어가는 버그 발생
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/domain/ThemeEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionEntity.java
  src/main/java/com/twentythree/peech/script/domain/VersionPk.java
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
  src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java
  src/main/java/com/twentythree/peech/script/repository/VersionRepository.java
  src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java
Labels: 버그

#248 TT-300 remaining time not null 제거
  src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java
Labels: 버그

#251 TT-302 spring actuator
  build.gradle
Labels: 기능구현

#254 TT-299 녹음 가능 최대 시간 수정
  src/main/java/com/twentythree/peech/usagetime/constant/ConstantValue.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
Labels: 수정

#256 TT-297 script 문장 순서 이상함
  src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
Labels: 버그

#257 TT-304 예상 시간 / 3
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
Labels: 수정

#259 TT-297 dtype modify 추가
  src/main/java/com/twentythree/peech/script/domain/InputAndSttType.java
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java
  src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
Labels: 버그

#260 TT-323 최대 녹음 시간 변경 및 여유 시간 설정
  src/main/java/com/twentythree/peech/usagetime/constant/ConstantValue.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
Labels: 수정

#261 fix: TT-290 시간 표시 법 변경
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
  src/test/java/com/twentythree/peech/common/utils/ScriptUtilsTest.java
Labels: 수정

#265 TT-334 수정 스크립트 문단별로 조회 시 순서가 정렬되지 않는 문제
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
  src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java
Labels: 버그

#266 bug: TT-334 예상시간 조회시 null 오류 해결
  src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
  src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
  src/main/java/com/twentythree/peech/script/service/SentenceService.java
  src/main/java/com/twentythree/peech/script/stt/service/CreateParagraghService.java
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
  src/main/java/com/twentythree/peech/usagetime/dto/response/CheckRemainingTimeResponseDTO.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
Labels: 버그

#267 TT-328 create user
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
  .github/workflows/cicd_dev.yml
  src/main/java/com/twentythree/peech/common/JwtProperties.java
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
  src/main/java/com/twentythree/peech/script/domain/ThemeEntity.java
  src/main/java/com/twentythree/peech/script/service/ThemeService.java
  src/main/java/com/twentythree/peech/usagetime/constant/UsageConstantValue.java
  src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java
  src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
  src/main/java/com/twentythree/peech/user/AuthorizationIdentifier.java
  src/main/java/com/twentythree/peech/user/AuthorizationServer.java
  src/main/java/com/twentythree/peech/user/UserGender.java
  src/main/java/com/twentythree/peech/user/UserRole.java
  src/main/java/com/twentythree/peech/user/UserStatus.java
  src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/domain/UserCreator.java
  src/main/java/com/twentythree/peech/user/domain/UserDomain.java
  src/main/java/com/twentythree/peech/user/domain/UserEntity.java
  src/main/java/com/twentythree/peech/user/domain/UserMapper.java
  src/main/java/com/twentythree/peech/user/dto/AccessAndRefreshToken.java
  src/main/java/com/twentythree/peech/user/dto/request/CreateUserRequestDTO.java
  src/main/java/com/twentythree/peech/user/dto/response/UserIdTokenResponseDTO.java
  src/main/java/com/twentythree/peech/user/entity/UserEntity.java
  src/main/java/com/twentythree/peech/user/repository/UserRepository.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/java/com/twentythree/peech/user/validator/UserValidator.java
  src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 기능구현

#271 TT-329 user delete
  src/main/java/com/twentythree/peech/common/utils/TimeUtils.java
  src/main/java/com/twentythree/peech/user/UserRole.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/domain/UserCreator.java
  src/main/java/com/twentythree/peech/user/domain/UserDeleter.java
  src/main/java/com/twentythree/peech/user/domain/UserDomain.java
  src/main/java/com/twentythree/peech/user/domain/UserFetcher.java
  src/main/java/com/twentythree/peech/user/dto/response/UserDeleteResponseDTO.java
  src/main/java/com/twentythree/peech/user/entity/UserEntity.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: 기능구현, 수정

#272 TT-328 create user 흐름 변경
  build.gradle
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
  src/main/java/com/twentythree/peech/config/OpenFeignConfig.java
  src/main/java/com/twentythree/peech/user/client/KakaoLoginClient.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/domain/UserCreator.java
  src/main/java/com/twentythree/peech/user/domain/UserDomain.java
  src/main/java/com/twentythree/peech/user/domain/UserFetcher.java
  src/main/java/com/twentythree/peech/user/domain/UserMapper.java
  src/main/java/com/twentythree/peech/user/dto/request/CompleteProfileRequestDTO.java
  src/main/java/com/twentythree/peech/user/dto/request/CreateUserRequestDTO.java
  src/main/java/com/twentythree/peech/user/dto/request/LoginBySocialRequestDTO.java
  src/main/java/com/twentythree/peech/user/dto/response/KakaoGetUserEmailResponseDTO.java
  src/main/java/com/twentythree/peech/user/dto/response/KakaoTokenDecodeResponseDTO.java
  src/main/java/com/twentythree/peech/user/entity/AuthorizationIdentifier.java
  src/main/java/com/twentythree/peech/user/entity/UserEntity.java
  src/main/java/com/twentythree/peech/user/repository/UserRepository.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/java/com/twentythree/peech/user/validator/UserValidator.java
  src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
  src/main/java/com/twentythree/peech/user/value/AuthorizationServer.java
  src/main/java/com/twentythree/peech/user/value/SignUpFinished.java
  src/main/java/com/twentythree/peech/user/value/UserGender.java
  src/main/java/com/twentythree/peech/user/value/UserRole.java
  src/main/java/com/twentythree/peech/user/value/UserStatus.java
  src/main/resources/data.sql
Labels: 기능구현, 수정

#275 TT-350 개발 서버 로깅 볼륨 설정
  .github/workflows/cd_prod.yml
Labels: 기능구현
