Repository twenty-three-23/peech, pull requests merged in 2024-09, with the labels that each got.

#341 TT-402
  .github/workflows/cicd_dev.yml
  Dockerfile
  src/main/java/com/twentythree/peech/config/WebConfig.java
Labels: 기능구현, 환경설정, 수정

#344 TT-406 음성 file 위치를 절대 경로로 변경
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
Labels: 버그

#345 TT-406 duration, remaining 타임 비교 부등호 수정
  src/main/java/com/twentythree/peech/script/stt/service/AudioChecker.java
Labels: 수정

#346 TT-406 actions을 2번 실행해야 하는 버그 해결
  .github/workflows/cd_prod.yml
  .github/workflows/cicd_dev.yml
Labels: 환경설정

#347 TT-406 duration, remaining 타임 비교 부등호 수정
  src/main/java/com/twentythree/peech/script/stt/service/AudioChecker.java
Labels: 수정

#349 TT-406 audioChecker checkRemainingAudioDuration! 제거
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
Labels: 수정

#350 TT-406 time을 totalRealSeconds로 변경
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
Labels: 수정

#355 TT-409
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
Labels: 수정

#360 TT-415 피드백 받기
  src/main/java/com/twentythree/peech/feedback/application/FeedbackService.java
  src/main/java/com/twentythree/peech/feedback/domain/FeedbackDomain.java
  src/main/java/com/twentythree/peech/feedback/domain/FeedbackMapper.java
  src/main/java/com/twentythree/peech/feedback/entity/Feedback.java
  src/main/java/com/twentythree/peech/feedback/infrastructure/FeedbackMapperImpl.java
  src/main/java/com/twentythree/peech/feedback/infrastructure/JpaFeedbackRepository.java
  src/main/java/com/twentythree/peech/feedback/presentation/FeedbackController.java
  src/main/java/com/twentythree/peech/feedback/value/request/CreateFeedbackRequestDTO.java
Labels: 기능구현

#358 TT-414 예상시간 정확도 상승
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
Labels: 기능구현

#361 v 1.1.1
  src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java
  src/main/java/com/twentythree/peech/feedback/application/FeedbackService.java
  src/main/java/com/twentythree/peech/feedback/domain/FeedbackDomain.java
  src/main/java/com/twentythree/peech/feedback/domain/FeedbackMapper.java
  src/main/java/com/twentythree/peech/feedback/entity/Feedback.java
  src/main/java/com/twentythree/peech/feedback/infrastructure/FeedbackMapperImpl.java
  src/main/java/com/twentythree/peech/feedback/infrastructure/JpaFeedbackRepository.java
  src/main/java/com/twentythree/peech/feedback/presentation/FeedbackController.java
  src/main/java/com/twentythree/peech/feedback/value/request/CreateFeedbackRequestDTO.java
Labels: 출시

#367 TT-422 애플로그인 검증 로직 수정
  src/main/java/com/twentythree/peech/user/dto/IdentityToken.java
  src/main/java/com/twentythree/peech/user/dto/IdentityTokenPayload.java
  src/main/java/com/twentythree/peech/user/dto/response/ApplePublicKeyResponseDTO.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
Labels: 수정

#370 TT-432 http method 추가
  src/main/java/com/twentythree/peech/common/interceptor/RequestLogInterceptor.java
Labels: 수정

#371 TT-436
  src/main/java/com/twentythree/peech/common/exception/BaseException.java
  src/main/java/com/twentythree/peech/script/stt/controller/STTController.java
  src/main/java/com/twentythree/peech/script/stt/dto/response/ClovaResponseDto.java
  src/main/java/com/twentythree/peech/script/stt/exception/STTException.java
  src/main/java/com/twentythree/peech/script/stt/service/AudioChecker.java
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
  src/main/java/com/twentythree/peech/script/stt/service/RequestClovaSpeechApiService.java
Labels: 수정
