Repository twenty-three-23/peech, pull requests merged in 2024-10, with the labels that each got.

#372 TT-454 예상 면접 질문
  src/main/java/com/twentythree/peech/interviewquestion/application/InterviewQuestionService.java
  src/main/java/com/twentythree/peech/interviewquestion/application/UserValidator.java
  src/main/java/com/twentythree/peech/interviewquestion/client/InterviewQuestionGPT.java
  src/main/java/com/twentythree/peech/interviewquestion/domain/InterviewQuestionDomain.java
  src/main/java/com/twentythree/peech/interviewquestion/domain/InterviewQuestionFetcher.java
  src/main/java/com/twentythree/peech/interviewquestion/domain/InterviewQuestionPredictor.java
  src/main/java/com/twentythree/peech/interviewquestion/dto/InterviewQuestionResponseDTO.java
  src/main/java/com/twentythree/peech/interviewquestion/infrastructure/InterviewQuestionInfra.java
  src/main/java/com/twentythree/peech/interviewquestion/presentation/InterviewQusetionControlloer.java
  src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
Labels: 기능구현

#373 TT-454 자기소개 만으로 면접질문 생성
  src/main/java/com/twentythree/peech/interviewquestion/application/InterviewQuestionService.java
  src/main/java/com/twentythree/peech/interviewquestion/domain/InterviewQuestionPredictor.java
  src/main/java/com/twentythree/peech/interviewquestion/dto/InterviewQuestionRequestDTO.java
  src/main/java/com/twentythree/peech/interviewquestion/presentation/InterviewQusetionControlloer.java
Labels: 기능구현

#377 TT-459
  src/main/java/com/twentythree/peech/script/validator/ThemeValidator.java
  src/main/java/com/twentythree/peech/script/validator/ThemeValidatorImpl.java
Labels: 버그

#386 TT-493
  src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java
  src/main/java/com/twentythree/peech/script/dto/ParagraphExpectedTimeDTO.java
  src/main/java/com/twentythree/peech/script/service/ScriptService.java
Labels: 수정

#387 TT-493
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
Labels: 버그

#388 TT-493
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
Labels: 버그

#389 TT-493
  .github/workflows/cicd_dev.yml
Labels: 버그
