Repository twenty-three-23/peech, pull requests merged in 2024-08, with the labels that each got.

#277 TT-350 logs 디렉토리에 쓰기 권한 부여
  .github/workflows/cd_prod.yml
Labels: 핫픽스

#278 TT-350 ssh 연결이 끊김
  .github/workflows/cicd_dev.yml
Labels: 핫픽스

#279 TT-350
  .github/workflows/cd_prod.yml
Labels: 핫픽스

#280 TT-352 유저에서 소셜 아이디 제거
  .github/workflows/cd_prod.yml
  src/main/java/com/twentythree/peech/user/domain/UserCreator.java
  src/main/java/com/twentythree/peech/user/domain/UserDomain.java
  src/main/java/com/twentythree/peech/user/domain/UserFetcher.java
  src/main/java/com/twentythree/peech/user/domain/UserMapper.java
  src/main/java/com/twentythree/peech/user/entity/AuthorizationIdentifier.java
  src/main/java/com/twentythree/peech/user/entity/UserEntity.java
  src/main/java/com/twentythree/peech/user/repository/UserRepository.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/java/com/twentythree/peech/user/validator/UserValidator.java
  src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
  src/main/resources/data.sql
Labels: 리팩토링

#281 TT-349 apple sign in
  src/main/java/com/twentythree/peech/common/exception/BaseException.java
  src/main/java/com/twentythree/peech/common/exception/Unauthorized.java
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
  src/main/java/com/twentythree/peech/user/client/AppleLoginClient.java
  src/main/java/com/twentythree/peech/user/dto/ApplePublicKey.java
  src/main/java/com/twentythree/peech/user/dto/IdentityToken.java
  src/main/java/com/twentythree/peech/user/dto/IdentityTokenHeader.java
  src/main/java/com/twentythree/peech/user/dto/IdentityTokenPayload.java
  src/main/java/com/twentythree/peech/user/dto/response/ApplePublicKeyResponseDTO.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/test/java/com/twentythree/peech/common/utils/JWTUtilsTest.java
Labels: 기능구현

#289 TT-355 카카오 로그인 역직렬화 해결
  src/main/java/com/twentythree/peech/user/client/KakaoLoginClient.java
  src/main/java/com/twentythree/peech/user/dto/KakaoAccount.java
  src/main/java/com/twentythree/peech/user/dto/response/KakaoGetUserEmailResponseDTO.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/java/com/twentythree/peech/user/validator/UserValidator.java
  src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
Labels: 버그

#291 TT-356 exception 로깅을 위한 sentry 세팅
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
  .github/workflows/cicd_dev.yml
  build.gradle
  src/main/resources/application.yml
Labels: 환경설정

#287 TT-351 get user by token
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/domain/UserFetcher.java
  src/main/java/com/twentythree/peech/user/dto/response/GetUserInformationResponseDTO.java
  src/main/java/com/twentythree/peech/user/repository/UserRepository.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
Labels: 기능구현

#298 TT-359 회원가입에서 sign up finished에 맞춰 상태를 body에 담아서 전송
  src/main/java/com/twentythree/peech/common/dto/response/WrappedResponseBody.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
Labels: 수정

#302 TT-376 @LoginUserId를 SecurityContextHolder로 변경
  src/main/java/com/twentythree/peech/auth/config/ArgumentResolverConfig.java
  src/main/java/com/twentythree/peech/auth/dto/LoginUserId.java
  src/main/java/com/twentythree/peech/auth/dto/UserIdDTO.java
  src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java
  src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
  src/main/java/com/twentythree/peech/auth/service/SecurityContextHolder.java
  src/main/java/com/twentythree/peech/common/interceptor/RequestLogInterceptor.java
  src/main/java/com/twentythree/peech/script/controller/ScriptController.java
  src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java
  src/main/java/com/twentythree/peech/script/controller/SwaggerThemeInterface.java
  src/main/java/com/twentythree/peech/script/controller/ThemeController.java
  src/main/java/com/twentythree/peech/script/stt/controller/STTController.java
  src/main/java/com/twentythree/peech/script/stt/controller/SwaggerSTTController.java
  src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java
  src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java
Labels: 버그, 수정

#304 !TT-377 null 처리
  src/main/java/com/twentythree/peech/common/interceptor/RequestLogInterceptor.java
Labels: 버그

#300 TT-361 문단별 핵심단어 추출 및 응답
  src/main/java/com/twentythree/peech/paragraph/application/ParagraphService.java
  src/main/java/com/twentythree/peech/paragraph/client/FeignInterceptor.java
  src/main/java/com/twentythree/peech/paragraph/client/GPTClient.java
  src/main/java/com/twentythree/peech/paragraph/domain/KeywordExtractor.java
  src/main/java/com/twentythree/peech/paragraph/domain/ParagraphFetcher.java
  src/main/java/com/twentythree/peech/paragraph/domain/ParagraphsDomain.java
  src/main/java/com/twentythree/peech/paragraph/dto/KeyWordsByParagraph.java
  src/main/java/com/twentythree/peech/paragraph/dto/response/KeyWordsByParagraphsResponseDTO.java
  src/main/java/com/twentythree/peech/paragraph/infrastructure/ParagraphFetcherImpl.java
  src/main/java/com/twentythree/peech/paragraph/presentation/ParagraphController.java
  src/main/java/com/twentythree/peech/paragraph/valueobject/Paragraph.java
  src/main/resources/data.sql
  src/test/java/com/twentythree/peech/paragraph/infrastructure/ParagraphFetcherImplTest.java
Labels: 기능구현, 테스트

#306 v1.1 -> v 1
  src/main/java/com/twentythree/peech/paragraph/client/GPTClient.java
Labels: 버그, 수정

#308 TT-379 로그 파일 일자별 생성
  src/main/resources/spring-logback.xml
Labels: 버그

#314 TT-380 이미 완전 가입된 유저가 로그인 할 떄
  src/main/java/com/twentythree/peech/user/controller/UserController.java
  src/main/java/com/twentythree/peech/user/domain/UserFetcher.java
  src/main/java/com/twentythree/peech/user/dto/LoginBySocial.java
  src/main/java/com/twentythree/peech/user/service/UserService.java
  src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
  src/main/java/com/twentythree/peech/user/validator/UserValidator.java
  src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
Labels: 버그

#316 TT-381 app info
  src/main/java/com/twentythree/peech/common/app/AppInfo.java
  src/main/java/com/twentythree/peech/common/app/AppInfoController.java
Labels: 기능구현

#317 TT-381 security setting 변경
  src/main/java/com/twentythree/peech/security/config/SecurityConfig.java
Labels: 수정

#319 fix: TT-382 max autio time 25분
  src/main/java/com/twentythree/peech/usagetime/constant/UsageConstantValue.java
Labels: 수정

#321 TT-382 restController로 변경
  src/main/java/com/twentythree/peech/common/app/AppInfoController.java
Labels: 수정

#323 TT-385 reissue 요청시 안되는 문제 발생
  src/main/java/com/twentythree/peech/auth/controller/AuthController.java
  src/main/java/com/twentythree/peech/auth/service/ReissueAccessAndRefreshTokenService.java
  src/main/java/com/twentythree/peech/security/config/SecurityConfig.java
  src/main/java/com/twentythree/peech/security/dto/RequestInformationDTO.java
  src/main/java/com/twentythree/peech/security/filter/JWTAuthenticationFilter.java
Labels: 버그

#327 TT-387 access, refresh token expiredTime 초기화
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
  src/main/java/com/twentythree/peech/user/controller/UserController.java
Labels: 버그

#328 TT-385 token 유효시간 원상복구
  src/main/java/com/twentythree/peech/common/utils/JWTUtils.java
Labels: 수정

#330 TT-388 app 버전 환경변수화
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
  .github/workflows/cicd_dev.yml
  src/main/java/com/twentythree/peech/common/app/AppInfoController.java
  src/main/resources/application.yml
Labels: 수정

#331 TT-388
  src/main/resources/application.yml
Labels: 수정

#333 TT-393 성별 UNKNOWN 추가
  src/main/java/com/twentythree/peech/user/value/UserGender.java
Labels: 버그

#335 feat: cors 해제
  src/main/java/com/twentythree/peech/config/WebConfig.java
Labels: 환경설정

#336 feat: cors 해제
  src/main/java/com/twentythree/peech/config/WebConfig.java
Labels: 환경설정

#337 fix: cors 수정
  src/main/java/com/twentythree/peech/config/WebConfig.java
Labels: 환경설정

#338 TT-402 웹에서 STT동작 및 음성 길이 확인
  .github/workflows/cd_prod.yml
  .github/workflows/ci_prod.yml
  .github/workflows/cicd_dev.yml
  build.gradle
  src/main/java/com/twentythree/peech/common/utils/ExtractDuration.java
  src/main/java/com/twentythree/peech/common/utils/FileUtils.java
  src/main/java/com/twentythree/peech/config/FFMPEGConfig.java
  src/main/java/com/twentythree/peech/script/stt/controller/STTController.java
  src/main/java/com/twentythree/peech/script/stt/dto/request/STTRequest2DTO.java
  src/main/java/com/twentythree/peech/script/stt/service/AudioChecker.java
  src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
  src/main/resources/application.yml
Labels: 기능구현, 수정

#339 TT-402 docker 에서 ffmpeg
  .github/workflows/cd_prod.yml
  .github/workflows/cicd_dev.yml
  Dockerfile
Labels: 수정
